config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
    chmod: '644'
  d_waybar:
    src: config/waybar
    dst: ~/.config/waybar
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
    chmod: '644'
  f_starship.toml:
    src: config/starship.toml
    dst: ~/.config/starship.toml
    chmod: '664'
  d_wofi:
    src: config/wofi
    dst: ~/.config/wofi
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
    chmod: '755'
  f_config:
    src: config/cava/config
    dst: ~/.config/cava/config
    chmod: '644'
  f_p10k.zsh:
    src: p10k.zsh
    dst: ~/.p10k.zsh
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  d_qtile:
    src: config/qtile
    dst: ~/.config/qtile
  d_niri:
    src: config/niri
    dst: ~/.config/niri
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
    chmod: '775'
  d_fuzzel:
    src: config/fuzzel
    dst: ~/.config/fuzzel
profiles:
  urano-lnx:
    dotfiles:
    - f_zshrc
    - d_waybar
    - f_bashrc
    - f_starship.toml
    - d_wofi
    - d_kitty
    - f_config
    - f_vimrc
    - d_qtile
    - d_niri
    - d_nvim
  tierra-lnx:
    dotfiles:
    - f_zshrc
    - d_waybar
    - f_zshrc
    - f_starship.toml
    - d_wofi
    - f_bashrc
    - d_kitty
    - f_p10k.zsh
    - f_vimrc
    - d_fuzzel
